name=Sequential
version=1.0.0
author=Jorge Iván Salinas Baltazar <jorgeivaneisaac@gmail.com>
maintainer=Jorge Iván Salinas Baltazar <jorgeivaneisaac@gmail.com>
sentence=Librería para el control de secuencias en Arduino.
paragraph=Permite gestionar secuencias de tareas y eventos de forma sencilla y eficiente.
category=Timing
url=https://github.com/jorgeivaneisaac-hub/Sequential.git
architectures=*
includes=sequential.hpp
