name=Sequential
version=1.0.0
author=Tu Nombre <tu@email.com>
maintainer=Tu Nombre <tu@email.com>
sentence=Librería para el control de secuencias en Arduino.
paragraph=Permite gestionar secuencias de tareas y eventos de forma sencilla y eficiente.
category=Timing
url=https://github.com/jorgeivaneisaac-hub/Sequential.git
architectures=*
includes=sequential.hpp
